version: "3.8"
services:
  mysql:
    image: mariadb:10.6
    container_name: mysql-intro-fastapi
    working_dir: /application
    volumes:
      - .:/application
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
